---
- name: Configure Git to add /opt/stage_5b as a safe directory
  shell: git config --global --add safe.directory "{{ app_dir }}"

- name: Clone the PHP project repo
  git: 
    repo: "{{ app_repo }}"
    dest: "{{ app_dir }}"
    single_branch: yes
    version: "{{ repo_branch }}"
    force: yes
    update: yes
    
- name: Switch to the php app directory
  command: chdir="{{ app_dir }}" ls

- name: copy .env file to the app directory
  copy:
    src: ./templates/env
    dest: "{{ app_dir }}.env"

- name: Change file ownership, group and permissions
  file:
    path: "{{ app_dir }}"
    state: directory
    recurse: true
    owner: hng
    group: hng
    mode: '0755'
  