---
- name: install dependencies
  apt: name={{item}} state=present update_cache=yes
  loop:
    - lsb-release
    - apt-transport-https
    - ca-certificates
    - gnupg2
    - debconf-utils

- name: Add ondrej repository for later versions of PHP
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: install PHP and its dependencies
  apt: "name={{ item }} state=present"
  loop:
    - php8.3
    - libapache2-mod-php
    - php8.3-mysql
    - php8.3-common
    - php8.3-pdo
    - php8.3-pgsql
    - php8.3-xml
    - php8.3-xmlrpc
    - php8.3-curl
    - php8.3-gd
    - php8.3-imagick
    - php8.3-cli
    - php8.3-dev
    - php8.3-imap
    - php8.3-mbstring
    - php8.3-opcache
    - php8.3-soap
    - php8.3-zip
    - php8.3-dom
    - php8.3-intl

- name: Install PostgreSQL and dependencies
  apt: name={{ item }} state=latest update_cache=yes
  loop:
    - postgresql
    - postgresql-contrib
    - libpq-dev
    - python3-psycopg2

- name: Install ACL, required for ansible super user escalation
  apt: name=acl state=present update_cache=yes

- name: install Redis
  apt: 
    name: redis 
    update_cache: yes

