---
- name: Run php artisan
  shell: "{{item}} chdir={{ app_dir }}"
  loop:
    - php artisan key:generate --force
    - php artisan config:cache
    - php artisan config:clear

- name: Run artisan migrate
  become: true
  shell: >
    php artisan migrate:fresh --force

- name: Run seed migrate
  become: true
  shell: >
    php artisan migrate --seed --force

- name: Run artisan serve
  become: true
  shell: >
    php artisan serve