---
- name: Run php artisan
  shell: "{{item}} chdir={{ app_dir }}"
  loop:
    - php artisan key:generate --force
    - php artisan config:cache
    - php artisan config:clear
  become_user: hng

- name: Run artisan migrate
  shell: >
    php artisan migrate:fresh --force
    chdir="{{ app_dir }}"
  register: migrate_result
  become_user: hng

- name: Display artisan migrate result
  debug:
    var: migrate_result

- name: Run seed migrate
  shell: >
    php artisan migrate --seed --force
    chdir={{ app_dir }}
  become_user: hng

- name: Run artisan serve
  shell: >
    php artisan serve
    chdir={{ app_dir }}
  become_user: hng

