---
- name: Run php artisan
  shell: "{{item}} chdir={{ app_dir }}"
  loop:
    - php artisan key:generate --force
    - php artisan config:cache
    - php artisan config:clear
  become_user: hng

- name: Run artisan migrate
  shell: >
    php artisan migrate:fresh --force
  become_user: hng

- name: Run seed migrate
  shell: >
    php artisan migrate --seed --force
  become_user: hng

- name: Run artisan serve
  shell: >
    php artisan serve
  become_user: hng