---
- name: Download Composer installer
  shell: curl -sS https://getcomposer.org/installer | php

- name: Move composer into globally-accessible location
  shell: >
    mv composer.phar "{{ composer_path }}"
    creates="{{ composer_path }}"

- name: change permission setting for composer
  shell: chmod +x "{{ composer_path }}"

- name: Run composer update
  shell: >
    composer update --no-interaction
    chdir="{{ app_dir }}"
  register: composer_update_result
  failed_when: composer_update_result.rc != 0 and "'already exists' not in composer_update_result.stderr"

- name: Display composer update result
  debug:
    var: composer_update_result

- name: run composer installer
  shell: >
    composer install --no-interaction
    chdir="{{ app_dir }}"
  
