---
- name: Install Nginx 1.26
  block:
    - name: Add Nginx signing key
      apt_key:
        url: https://nginx.org/keys/nginx_signing.key
        state: present
    - name: Add Nginx repository
      apt_repository:
        repo: deb https://nginx.org/packages/ubuntu/ jammy nginx
        state: present
        filename: nginx
    - name: Install Nginx 1.26
      apt:
        name: nginx=1.26.*
        state: present
        update_cache: yes

- name: Start NGINX
  systemd:
    name: nginx
    state: started

- name: Verify NGINX is running
  command: curl -I 127.0.0.1
  register: nginx_status

- name: Display NGINX status
  debug:
    msg: "{{ nginx_status.stdout }}"

- name: Configure Nginx as a reverse proxy
  template:
    src: ./templates/nginx.conf.j2
    dest: /etc/nginx/conf.d/default.conf

- name: Test Nginx configuration
  shell: nginx -t
  notify: Restart Nginx